version: '3.0'

services:
  main:
    container_name: back-end[lets-talk]-conteiner
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - 5000:5000
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres-conteiner
    image: postgres:14.0-alpine
    env_file:
      - .development.env
    environment:
      PG-DATA: ./var/lib/postgresql/data
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: